Presentation/Controllers/ActorController.cs
using Application.Commands.Actor;
using Application.Queries.Actor;
using Application.Responses;
using AutoMapper;
using Domain.Aggregates.IdentityAggregate;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize(Roles = Roles.Admin)]
public class ActorController : Controller
{
    #region Fields

    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    #endregion

    #region Constructors

    /// <summary>
    /// Initialize an instance of ActorController
    /// </summary>
    /// <param name="mapper">An abstract of Mapper</param>
	/// <param name="mediator">An anstract of Mediator</param>
    public ActorController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains the list of actors
    /// </summary>
    /// <returns>A view of actors</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var query = new GetActorsQuery();

        var actors = await _mediator.Send(query);

        var response = _mapper.Map<ICollection<ActorResponse>>(actors);

        return View(response);
    }

    /// <summary>
    /// Get the page of creating new actor
    /// </summary>
    /// <returns>A view of creating new actor</returns>
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// Create a new actor
    /// </summary>
    /// <param name="command">An command to create new actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost]
    public async Task<IActionResult> Create(CreateActorCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of actor details based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Details(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var reponse = await _mediator.Send(query);

        if (reponse is null)
        {
            return View("NotFound");
        }

        return View(reponse);
    }

    /// <summary>
    /// Get the page of editing actor based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    public async Task<IActionResult> Edit(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        var command = EditActorCommand.Create(response);

        return View(command);
    }

    /// <summary>
    /// Edit an actor by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor to edit</param>
    /// <param name="command">A command to edit an actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, EditActorCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        command.Id = id;

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of deleting actor based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    public async Task<IActionResult> Delete(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        return View(response);
    }

    /// <summary>
    /// Delete an actor by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor to delete</param>
    /// <param name="command">A command to delete an actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirm(Guid id, DeleteActorCommand command)
    {
        command.Id = id;

        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    #endregion
}

Presentation/Controllers/CinemaController.cs
using Application.Commands.Cinema;
using Application.Queries.Cinema;
using AutoMapper;
using Domain.Aggregates.IdentityAggregate;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize(Roles = Roles.Admin)]
public class CinemaController : Controller
{
    #region Fields

    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    #endregion

    #region Constructors

    /// <summary>
    /// Initialize an instance of CinemaController
    /// </summary>
    /// <param name="mapper">An abstract of Mapper</param>
    /// <param name="mediator">An abtract of Mediator</param>
    public CinemaController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains the list of cinemas
    /// </summary>
    /// <returns>A view of cinemas</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var query = new GetCinemasQuery();

        var allCinemas = await _mediator.Send(query);

        return View(allCinemas);
    }

    /// <summary>
    /// Get the page of creating new cinema
    /// </summary>
    /// <returns>A view of creating new cinema</returns>
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// Create a new cinema
    /// </summary>
    /// <param name="command">A command to create new cinema</param>
    /// <returns>Redirect to the page of cinemas</returns>
    [HttpPost]
    public async Task<IActionResult> Create(CreateCinemaCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of deleting cinema based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected cinema</param>
    /// <returns></returns>
    [AllowAnonymous]
    public async Task<IActionResult> Delete(Guid id)
    {
        var query = new GetCinemaByIdQuery(id);

        var cinema = await _mediator.Send(query);

        if (cinema is null)
        {
            return View("NotFound");
        }

        return View(cinema);
    }

    /// <summary>
    /// Delete a cinema by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected cinema to delete</param>
    /// <returns>Redirect to the page of cinemas</returns>
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirm(Guid id, DeleteCinemaCommand command)
    {
        command.Id = id;

        var query = new GetCinemaByIdQuery(id);

        var cinema = await _mediator.Send(query);

        if (cinema is null)
        {
            return View("NotFound");
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of cinema details by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected cinema</param>
    /// <returns>A view of cinema details</returns>
    public async Task<IActionResult> Details(Guid id)
    {
        var query = new GetCinemaByIdQuery(id);

        var cinema = await _mediator.Send(query);

        if (cinema is null)
        {
            return View("NotFound");
        }

        return View(cinema);
    }

    /// <summary>
    /// Get the page of editing cinema based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected cinema</param>
    /// <returns>A view of editing cinema with details</returns>
    public async Task<IActionResult> Edit(Guid id)
    {
        var query = new GetCinemaByIdQuery(id);

        var cinema = await _mediator.Send(query);

        if (cinema is null)
        {
            return View("NotFound");
        }

        var command = EditCinemaCommand.Create(cinema);

        return View(command);
    }

    /// <summary>
    /// Edit a cinema by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected cinema to edit</param>
    /// <param name="command">A command to edit a cinema</param>
    /// <returns>Redirect to the page of cinemas</returns>
    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, EditCinemaCommand command)
    {
        command.Id = id;

        var query = new GetCinemaByIdQuery(id);

        var cinema = await _mediator.Send(query);

        if (cinema is null)
        {
            return View("NotFound");
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    #endregion
}

Presentation/Controllers/OrderController.cs
using Application.Commands.Order;
using Application.Queries.Movie;
using Application.Queries.Orders;
using Application.Services;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize]
public class OrderController : Controller
{
    #region Fields

    private readonly ShoppingCartService _shoppingCartService;
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    #endregion

    #region Constructors

    public OrderController(ShoppingCartService shoppingCartService,
                           IMapper mapper,
                           IMediator mediator)
    {
        _shoppingCartService = shoppingCartService;
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains a list of orders
    /// </summary>
    /// <returns>A view of orders</returns>
    public async Task<IActionResult> Index()
    {
        Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        string role = User.FindFirstValue(ClaimTypes.Role);

        var query = new GetOrdersQuery(userId, role);

        var orders = await _mediator.Send(query);

        return View(orders);
    }

    /// <summary>
    /// Get page the shopping cart
    /// </summary>
    /// <param name="movieName">A movie name to get expected cart item</param>
    /// <param name="moviePrice">A movie price to get cart item price</param>
    /// <returns>A view of shopping cart</returns>
    public async Task<IActionResult> ShoppingCart(string movieName, double moviePrice)
    {
        var items = await _shoppingCartService.GetShoppingCartItemsAsync();
        var total = await _shoppingCartService.GetShoppingCartTotalAsync();

        _shoppingCartService.ShoppingCartItems = items;

        ShoppingCartViewModel response = new()
        {
            MovieName = movieName,
            MoviePrice = moviePrice,
            ShoppingCartService = _shoppingCartService,
            ShoppingCartTotal = total
        };

        return View(response);
    }

    /// <summary>
    /// Add movie item into shopping cart
    /// </summary>
    /// <param name="id">Id to retrieve an expected movie item</param>
    /// <returns>Redirect to the page of shopping cart</returns>
    public async Task<RedirectToActionResult> AddItemToShoppingCart(Guid id)
    {
        var query = new GetMovieByIdQuery(id);

        var response = await _mediator.Send(query);

        await _shoppingCartService.AddItemToCartAsync(id);

        return RedirectToAction(nameof(ShoppingCart), new { movieName = response.Name, moviePrice = response.Price });
    }

    /// <summary>
    /// Remove movie item from the shopping cart
    /// </summary>
    /// <param name="id">Id to retrieve an expexted movie item</param>
    /// <returns>Redirect to the page of shopping cart</returns>
    public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(Guid id)
    {
        var query = new GetMovieByIdQuery(id);

        var response = await _mediator.Send(query);

        await _shoppingCartService.RemoveItemFromCartAsync(id);

        return RedirectToAction(nameof(ShoppingCart), new { movieName = response.Name, moviePrice = response.Price });
    }

    /// <summary>
    /// Make new order
    /// </summary>
    /// <returns>A view that announces the order is completed</returns>
    /// <exception cref="Exception">An exception that is thrown if there is no user identifier</exception>
    public async Task<IActionResult> MakeOrder()
    {
        var items = await _shoppingCartService.GetShoppingCartItemsAsync();

        Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("Invalid or missing user identifier"));
        string email = User.FindFirstValue(ClaimTypes.Email);

        var command = new StoreOrderCommand(items, userId, email);

        await _mediator.Send(command);
        await _shoppingCartService.ClearShoppingCartAsync();

        return View("OrderCompleted");
    }

    #endregion
}

Presentation/Views/Movie/Create.cshtml
@using Core.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model Application.Commands.Movie.CreateMovieCommand

@{
	ViewData["Title"] = "Create a new movie";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<h4>Create a new movie</h4>
		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Create">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="row">
						<div class="col-md-6">
							<div class="mb-3">
								<label asp-for="Name" class="form-label"></label>
								<input asp-for="Name" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="StartDate" class="form-label"></label>
								<input asp-for="StartDate" class="form-control" />
								<span asp-validation-for="StartDate" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="EndDate" class="form-label"></label>
								<input asp-for="EndDate" class="form-control" />
								<span asp-validation-for="EndDate" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="Price" class="form-label"></label>
								<input asp-for="Price" class="form-control" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ImageUrl" class="form-label"></label>
								<input asp-for="ImageUrl" class="form-control" />
								<span asp-validation-for="ImageUrl" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="mb-3">
								<label asp-for="CinemaId" class="form-label"></label>
								<select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
								<span asp-validation-for="CinemaId" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="MovieCategory" class="form-label"></label>
								<select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
								<span asp-validation-for="MovieCategory" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ProducerId" class="form-label"></label>
								<select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
								<span asp-validation-for="ProducerId" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ActorIds" class="form-label"></label>
								<select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
								<span asp-validation-for="ActorIds" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-12">
							<div class="mb-3">
								<label asp-for="Description" class="form-label"></label>
								<textarea asp-for="Description" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="col-md-4 offset-4 text-center">
						<img width="100%" id="ImageUrlPreview" />
					</div>
					<div class="mb-3">
						<input type="submit" value="Create" class="btn btn-outline-success float-end" />
						<a class="btn btn-outline-secondary" asp-action="Index">Go to list</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script>
		$("#ImageUrl").on("change", function () {
			let output = document.getElementById("ImageUrlPreview");
			output.src = $(this).val();
		})
	</script>
}

Presentation/Views/Movie/Details.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model Application.Responses.MovieResponse

@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <h5 class="card-title">
                            @Model.Name
                        </h5>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinema" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Category: </b>@Model.MovieCategory
                        </p>
                        <p class="card-text">
                            <b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")
                        </p>
                        <p class="card-text">
                            <b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")
                        </p>
                        <p class="card-text">

                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                        <b>Actors: </b>
                        <hr/>
                        <div class="row">
                            @foreach (var actor in Model.ActorsMovies)
                            {
                                <div class="col text-center">
                                    <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureUrl" style="max-width: 150px" />
                                    <br/>
                                    <a asp-controller="Actor" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-end" asp-action="Index">
                                Back to list
                            </a>
                            <a class="btn btn-success @(DateTime.Now > Model.EndDate ? "disabled" : "")" asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Presentation/Views/Movie/Edit.cshtml
@using Core.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model Application.Commands.Movie.EditMovieCommand

@{
	ViewData["Title"] = "Update movie";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<h4>Update movie</h4>
		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Edit">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="row">
						<div class="col-md-6">
							<div class="mb-3">
								<label asp-for="Name" class="form-label"></label>
								<input asp-for="Name" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="StartDate" class="form-label"></label>
								<input asp-for="StartDate" class="form-control" />
								<span asp-validation-for="StartDate" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="EndDate" class="form-label"></label>
								<input asp-for="EndDate" class="form-control" />
								<span asp-validation-for="EndDate" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="Price" class="form-label"></label>
								<input asp-for="Price" class="form-control" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ImageUrl" class="form-label"></label>
								<input asp-for="ImageUrl" class="form-control" />
								<span asp-validation-for="ImageUrl" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="mb-3">
								<label asp-for="CinemaId" class="form-label"></label>
								<select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
								<span asp-validation-for="CinemaId" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="MovieCategory" class="form-label"></label>
								<select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
								<span asp-validation-for="MovieCategory" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ProducerId" class="form-label"></label>
								<select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
								<span asp-validation-for="ProducerId" class="text-danger"></span>
							</div>
							<div class="mb-3">
								<label asp-for="ActorIds" class="form-label"></label>
								<select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
								<span asp-validation-for="ActorIds" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-12">
							<div class="mb-3">
								<label asp-for="Description" class="form-label"></label>
								<textarea asp-for="Description" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="col-md-4 offset-4 text-center">
						<img width="100%" id="ImageUrlPreview" />
					</div>
					<div class="mb-3">
						<input type="submit" value="Edit" class="btn btn-outline-success float-end" />
						<a class="btn btn-outline-secondary" asp-action="Index">Go to list</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script>
		$(document).ready(function () {
			let output = document.getElementById("ImageUrlPreview");
			output.src = $("#ImageUrl").val();
		})
		
		$("#ImageUrl").on("change", function () {
			let output = document.getElementById("ImageUrlPreview");
			output.src = $(this).val();
		})
	</script>
}

Presentation/Views/Movie/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<Application.Responses.MovieResponse>

@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 col-md-3 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <h5 class="card-title">
                                @item.Name
                                @if (User.Identity is { IsAuthenticated: true } && User.IsInRole("Admin"))
                                {
                                    <a class="text-white float-end" asp-action="Edit" asp-route-id="@item.Id">
                                        <i class="bi bi-pencil-square"></i>
                                    </a>
                                }
                            </h5>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text">
                                <b>Cinema: </b>@item.Cinema.Name
                            </p>
                            <p class="card-text">
                                <b>Category: </b>@item.MovieCategory
                            </p>
                            <p class="card-text">
                                <b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")
                            </p>
                            <p class="card-text">
                                <b>End Date: </b>@item.EndDate.ToString("dd MMM yy")
                            </p>
                            <p class="card-text">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-end" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success @(DateTime.Now > item.EndDate ? "disabled" : "")" asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Movie");