Presentation/Controllers/ActorController.cs
using Application.Commands.Actor;
using Application.Queries.Actor;
using Application.Responses;
using AutoMapper;
using Domain.Aggregates.IdentityAggregate;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize(Roles = Roles.Admin)]
public class ActorController : Controller
{
    #region Fields

    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    #endregion

    #region Constructors

    /// <summary>
    /// Initialize an instance of ActorController
    /// </summary>
    /// <param name="mapper">An abstract of Mapper</param>
	/// <param name="mediator">An anstract of Mediator</param>
    public ActorController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains the list of actors
    /// </summary>
    /// <returns>A view of actors</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var query = new GetActorsQuery();

        var actors = await _mediator.Send(query);

        var response = _mapper.Map<ICollection<ActorResponse>>(actors);

        return View(response);
    }

    /// <summary>
    /// Get the page of creating new actor
    /// </summary>
    /// <returns>A view of creating new actor</returns>
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// Create a new actor
    /// </summary>
    /// <param name="command">An command to create new actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost]
    public async Task<IActionResult> Create(CreateActorCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of actor details based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Details(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var reponse = await _mediator.Send(query);

        if (reponse is null)
        {
            return View("NotFound");
        }

        return View(reponse);
    }

    /// <summary>
    /// Get the page of editing actor based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    public async Task<IActionResult> Edit(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        var command = EditActorCommand.Create(response);

        return View(command);
    }

    /// <summary>
    /// Edit an actor by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor to edit</param>
    /// <param name="command">A command to edit an actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, EditActorCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        command.Id = id;

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of deleting actor based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor</param>
    /// <returns>A view of actor details</returns>
    public async Task<IActionResult> Delete(Guid id)
    {
        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        return View(response);
    }

    /// <summary>
    /// Delete an actor by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected actor to delete</param>
    /// <param name="command">A command to delete an actor</param>
    /// <returns>Redirect to the page of actors</returns>
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirm(Guid id, DeleteActorCommand command)
    {
        command.Id = id;

        var query = new GetActorByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    #endregion
}

Presentation/Controllers/MovieController.cs
using Application.Commands.Movie;
using Application.Queries.Movie;
using AutoMapper;
using Domain.Aggregates.IdentityAggregate;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize(Roles = Roles.Admin)]
public class MovieController : Controller
{
    #region Fields

    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    #endregion

    #region Constructors

    /// <summary>
    /// Initialize an instance of MovieController
    /// </summary>
    /// <param name="mapper">An abstract of Mapper</param>
    /// <param name="mediator">An abstract of Mediator</param>
    public MovieController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains the list of movies
    /// </summary>
    /// <returns>A view of movies</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var query = new GetMoviesQuery();

        var response = await _mediator.Send(query);

        return View(response);
    }

    /// <summary>
    /// Search movies by name or description
    /// </summary>
    /// <param name="searchString">A string to search movie</param>
    /// <returns>A view of searched movies</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Filter(string searchString)
    {
        var query = new GetMoviesQuery();

        var response = await _mediator.Send(query);

        if (!string.IsNullOrEmpty(searchString))
        {
            var filteredResults = response.Where(n => n.Name.Contains(searchString, StringComparison.CurrentCultureIgnoreCase)
                                                       || n.Description.Contains(searchString, StringComparison.CurrentCultureIgnoreCase))
                                          .ToList();

            return View("Index", filteredResults);
        }

        return View("Index", response);
    }

    /// <summary>
    /// Get the page of movie details by id
    /// </summary>
    /// <param name="id">id to retrieve an expected movie</param>
    /// <returns>A view of movie details</returns>
    [AllowAnonymous]
    public async Task<IActionResult> Details(Guid id)
    {
        var query = new GetMovieIncludeByIdQuery(id);

        var response = await _mediator.Send(query);

        if (response is null)
        {
            return View("NotFound");
        }

        return View(response);
    }

    /// <summary>
    /// Get the page of creating new movie
    /// </summary>
    /// <returns>A view of creating new movie</returns>
    public async Task<IActionResult> Create()
    {
        var query = new GetNewMovieDropdownsValuesQuery();

        var movieDropdownsData = await _mediator.Send(query);

        ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

        return View();
    }

    /// <summary>
    /// Create a new movie
    /// </summary>
    /// <param name="command">A command to create new move</param>
    /// <returns>Redirect to the page of movies</returns>
    [HttpPost]
    public async Task<IActionResult> Create(CreateMovieCommand command)
    {
        if (!ModelState.IsValid)
        {
            var query = new GetNewMovieDropdownsValuesQuery();

            var movieDropdownsData = await _mediator.Send(query);

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(command);
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Get the page of editing movie based on id
    /// </summary>
    /// <param name="id">Id to retrieve an expected movie</param>
    /// <returns>A view of editing movie with details</returns>
    public async Task<IActionResult> Edit(Guid id)
    {
        var movieIncludeQuery = new GetMovieIncludeByIdQuery(id);

        var movieDetails = await _mediator.Send(movieIncludeQuery);

        if (movieDetails is null)
        {
            return View("NotFound");
        }

        var command = EditMovieCommand.Create(movieDetails);

        var movieDropdownQuery = new GetNewMovieDropdownsValuesQuery();

        var movieDropdownsData = await _mediator.Send(movieDropdownQuery);

        ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

        return View(command);
    }

    /// <summary>
    /// Edit a movie by id
    /// </summary>
    /// <param name="id">Id to retrieve an expected movie</param>
    /// <param name="command">A command to edit a movie</param>
    /// <returns>Redirect to the page of movies</returns>
    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, EditMovieCommand command)
    {
        if (!ModelState.IsValid)
        {
            var query = new GetNewMovieDropdownsValuesQuery();

            var movieDropdownsData = await _mediator.Send(query);

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(command);
        }

        await _mediator.Send(command);

        return RedirectToAction(nameof(Index));
    }

    #endregion
}

Presentation/Controllers/OrderController.cs
using Application.Commands.Order;
using Application.Queries.Movie;
using Application.Queries.Orders;
using Application.Services;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Presentation.Controllers;

[Authorize]
public class OrderController : Controller
{
    #region Fields

    private readonly ShoppingCartService _shoppingCartService;
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    #endregion

    #region Constructors

    public OrderController(ShoppingCartService shoppingCartService,
                           IMapper mapper,
                           IMediator mediator)
    {
        _shoppingCartService = shoppingCartService;
        _mapper = mapper;
        _mediator = mediator;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Get the page that contains a list of orders
    /// </summary>
    /// <returns>A view of orders</returns>
    public async Task<IActionResult> Index()
    {
        Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        string role = User.FindFirstValue(ClaimTypes.Role);

        var query = new GetOrdersQuery(userId, role);

        var orders = await _mediator.Send(query);

        return View(orders);
    }

    /// <summary>
    /// Get page the shopping cart
    /// </summary>
    /// <param name="movieName">A movie name to get expected cart item</param>
    /// <param name="moviePrice">A movie price to get cart item price</param>
    /// <returns>A view of shopping cart</returns>
    public async Task<IActionResult> ShoppingCart(string movieName, double moviePrice)
    {
        var items = await _shoppingCartService.GetShoppingCartItemsAsync();
        var total = await _shoppingCartService.GetShoppingCartTotalAsync();

        _shoppingCartService.ShoppingCartItems = items;

        ShoppingCartViewModel response = new()
        {
            MovieName = movieName,
            MoviePrice = moviePrice,
            ShoppingCartService = _shoppingCartService,
            ShoppingCartTotal = total
        };

        return View(response);
    }

    /// <summary>
    /// Add movie item into shopping cart
    /// </summary>
    /// <param name="id">Id to retrieve an expected movie item</param>
    /// <returns>Redirect to the page of shopping cart</returns>
    public async Task<RedirectToActionResult> AddItemToShoppingCart(Guid id)
    {
        var query = new GetMovieByIdQuery(id);

        var response = await _mediator.Send(query);

        await _shoppingCartService.AddItemToCartAsync(id);

        return RedirectToAction(nameof(ShoppingCart), new { movieName = response.Name, moviePrice = response.Price });
    }

    /// <summary>
    /// Remove movie item from the shopping cart
    /// </summary>
    /// <param name="id">Id to retrieve an expexted movie item</param>
    /// <returns>Redirect to the page of shopping cart</returns>
    public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(Guid id)
    {
        var query = new GetMovieByIdQuery(id);

        var response = await _mediator.Send(query);

        await _shoppingCartService.RemoveItemFromCartAsync(id);

        return RedirectToAction(nameof(ShoppingCart), new { movieName = response.Name, moviePrice = response.Price });
    }

    /// <summary>
    /// Make new order
    /// </summary>
    /// <returns>A view that announces the order is completed</returns>
    /// <exception cref="Exception">An exception that is thrown if there is no user identifier</exception>
    public async Task<IActionResult> MakeOrder()
    {
        var items = await _shoppingCartService.GetShoppingCartItemsAsync();

        Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("Invalid or missing user identifier"));
        string email = User.FindFirstValue(ClaimTypes.Email);

        var command = new StoreOrderCommand(items, userId, email);

        await _mediator.Send(command);
        await _shoppingCartService.ClearShoppingCartAsync();

        return View("OrderCompleted");
    }

    #endregion
}

Presentation/Views/Shared/NotFound.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<div class="row text-center">
	<div class="col-md-6 offset-3">
		<h1>404 Not Found</h1>
		<a class="btn btn-primary mt-4" asp-controller="Movie" asp-action="Index">Home Page</a>
	</div>
</div>

Presentation/Views/Shared/_CreateItem.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
	<div style="position: fixed; right: 25px; bottom: 25px;">
		<a asp-controller="@Model" asp-action="Create" class="btn btn-success">
			<i class="bi bi-plus-circle"></i> Add new
		</a>
	</div>
}

Presentation/Views/Shared/_Identity.cshtml
@using Domain.Aggregates.IdentityAggregate
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log In
    </a>
    <span style="padding: 5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-box-arrow-in-right"></i> Register
    </a>
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown" aria-expanded="False">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)!
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log Out
        </button>
    </form>
}

Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Presentation.ViewComponents
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/ETickets.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">ETickets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movie" asp-action="Index"><i class="badge-info bi-film"></i> Movies</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="row g-1 align-items-center" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        <div class="col-auto">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." />
                        </div>
                        <div class="col">
                            <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ETickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>